### Column Transformation in pandas

In [1]:
import pandas as pd

In [4]:
sdata=pd.read_csv("subdata_pandas/student1.csv")
sdata

    id firstName  lastName  age  marks   fees
0  101    Akshay    Shetty   20     85  25000
1  102    Ananya       Rao   21     92  30000
2  103     Rohit  Bhandary   19     76  28000
3  104     Nisha   D'Souza   20     88  25000
4  105   Karthik   Poojary   22     69  32000
5  106    Shreya    Shetty   19     95  30000
6  107     Rohan      Naik   21     72  27000
7  108   Deepika      Bhat   20     81  28000
8  109  Abhishek    Kotian   22     64  26000
9  110     Pooja       Rai   19     90  30000

In [5]:
sdata["id"]

0    101
1    102
2    103
3    104
4    105
5    106
6    107
7    108
8    109
9    110
Name: id, dtype: int64

In [6]:
sdata[["id","firstName"]]

    id firstName
0  101    Akshay
1  102    Ananya
2  103     Rohit
3  104     Nisha
4  105   Karthik
5  106    Shreya
6  107     Rohan
7  108   Deepika
8  109  Abhishek
9  110     Pooja

In [7]:
sdata.loc[sdata.firstName=="Karthik"]

    id firstName lastName  age  marks   fees
4  105   Karthik  Poojary   22     69  32000

In [14]:
sdata.loc[0,"lastName"]

'Shetty'

In [15]:
sdata.iloc[0:2, 0:2]

    id firstName
0  101    Akshay
1  102    Ananya

In [16]:
sdata.where(sdata['age']>20)

      id firstName lastName   age  marks     fees
0    NaN       NaN      NaN   NaN    NaN      NaN
1  102.0    Ananya      Rao  21.0   92.0  30000.0
2    NaN       NaN      NaN   NaN    NaN      NaN
3    NaN       NaN      NaN   NaN    NaN      NaN
4  105.0   Karthik  Poojary  22.0   69.0  32000.0
5    NaN       NaN      NaN   NaN    NaN      NaN
6  107.0     Rohan     Naik  21.0   72.0  27000.0
7    NaN       NaN      NaN   NaN    NaN      NaN
8  109.0  Abhishek   Kotian  22.0   64.0  26000.0
9    NaN       NaN      NaN   NaN    NaN      NaN

In [17]:
sdata.where(sdata['age']>20,other="Minor")

      id firstName lastName    age  marks   fees
0  Minor     Minor    Minor  Minor  Minor  Minor
1    102    Ananya      Rao     21     92  30000
2  Minor     Minor    Minor  Minor  Minor  Minor
3  Minor     Minor    Minor  Minor  Minor  Minor
4    105   Karthik  Poojary     22     69  32000
5  Minor     Minor    Minor  Minor  Minor  Minor
6    107     Rohan     Naik     21     72  27000
7  Minor     Minor    Minor  Minor  Minor  Minor
8    109  Abhishek   Kotian     22     64  26000
9  Minor     Minor    Minor  Minor  Minor  Minor

In [20]:
sdata.loc[(sdata["marks"]>=85,"Result")]="Selected"
sdata.loc[(sdata["marks"]<85,"Result")]="Not Selected"
sdata

    id firstName  lastName  age  marks   fees        Result
0  101    Akshay    Shetty   20     85  25000      Selected
1  102    Ananya       Rao   21     92  30000      Selected
2  103     Rohit  Bhandary   19     76  28000  Not Selected
3  104     Nisha   D'Souza   20     88  25000      Selected
4  105   Karthik   Poojary   22     69  32000  Not Selected
5  106    Shreya    Shetty   19     95  30000      Selected
6  107     Rohan      Naik   21     72  27000  Not Selected
7  108   Deepika      Bhat   20     81  28000  Not Selected
8  109  Abhishek    Kotian   22     64  26000  Not Selected
9  110     Pooja       Rai   19     90  30000      Selected

In [21]:
sdata["FullName"]=sdata["firstName"]+" "+sdata["lastName"]
sdata

    id firstName  lastName  age  marks   fees        Result         FullName
0  101    Akshay    Shetty   20     85  25000      Selected    Akshay Shetty
1  102    Ananya       Rao   21     92  30000      Selected       Ananya Rao
2  103     Rohit  Bhandary   19     76  28000  Not Selected   Rohit Bhandary
3  104     Nisha   D'Souza   20     88  25000      Selected    Nisha D'Souza
4  105   Karthik   Poojary   22     69  32000  Not Selected  Karthik Poojary
5  106    Shreya    Shetty   19     95  30000      Selected    Shreya Shetty
6  107     Rohan      Naik   21     72  27000  Not Selected       Rohan Naik
7  108   Deepika      Bhat   20     81  28000  Not Selected     Deepika Bhat
8  109  Abhishek    Kotian   22     64  26000  Not Selected  Abhishek Kotian
9  110     Pooja       Rai   19     90  30000      Selected        Pooja Rai